---

# To install pre-commit hooks, install `pre-commit` and activate it here:
#     pip3 install pre-commit
#     pre-commit install
#
# Run the hooks on all files with
# 'pre-commit run --all'
#

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint]
  - repo: https://github.com/brainelectronics/snippets2changelog
    rev: 1.7.0
    hooks:
      - id: snippets2changelog
        args:
          - "changelog"
          - "changelog.md"
          - "--snippets=.snippets"
          - "--no-internal"
  - repo: https://github.com/brainelectronics/changelog2version
    rev: 0.12.1
    hooks:
      - id: changelog2version
        args:
          - "--changelog_file=changelog.md.new"
          - "--version_file=be_upy_blink/version.py"
          - "--version_file_type=py"
          - "--validate"
  - repo: https://github.com/brainelectronics/micropython-package-validation
    rev: 0.8.0
    hooks:
      - id: upy-package
        name: upy-package
        args:
          - "--setup_file=setup.py"
          - "--package_changelog_file=changelog.md.new"
          - "--package_file=package.json"
          - "--validate"
          - "--pretty"
  - repo: local
    hooks:
      - id: mpy-cross
        name: Create mpy files
        entry: sh scripts/convert_to_mpy.sh be_upy_blink/
        language: python
        pass_filenames: false
        types: [file, python]
        additional_dependencies:
          - "mpy-cross"
  - repo: https://github.com/brainelectronics/micropython-package-validation
    rev: 0.8.0
    hooks:
      - id: upy-package
        name: upy-package-mpy
        args:
          - "--setup_file=setup.py"
          - "--package_changelog_file=changelog.md.new"
          - "--package_file=package_mpy.json"
          - "--package_file_glob=*.mpy"
          - "--validate"
          - "--pretty"
